### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by 6xthFNGR** [M-Reimer/savescreenshot#37]
Hello Manuel!

1.) I really appreciate all your addons! I use multiple of your addons!.
2.) This addon together with FireShot is the ONLY addon that does real Full Webpage Screenshots for free! Amazing
3.) Your App uses no external service for this, just the internal features, or? -> Thas a huge benefit to FireShot

Issues:
I am just missing support to save into a PDF.
I can do this with just a local pdf printer, but it would be great to save this step!

Except of that, no requests what so ever.

One last bit: I try to contact you because I have a really simple Addon Idea which would be amazing if you can code it.
I just need a toggle for switching dom.event.clipboardevents.enabled on and off.

I would be happy to donate some coffee by PayPal for that!

Many Thanks

**Comment by M-Reimer** [comment]
Thanks for your feedback!

> 3.) Your App uses no external service for this, just the internal features, or? -> Thas a huge benefit to FireShot

Exactly. All my Add-ons use internal features combined with my own code. No external services are used and all my Add-ons are without ads or tracking.

> I am just missing support to save into a PDF.
> I can do this with just a local pdf printer, but it would be great to save this step!

This does not belong into a screenshot Add-on. Screenshots are, by definition, pixel perfect "photos" of the screen which also means that the result usually is a raster image. This is no good idea at all for PDF where you should use the vector capabilities of PDF. And to do this you always want to go the route over some kind of "printer interface".

I recommend this Add-on for this task: https://addons.mozilla.org/firefox/addon/print-edit-we/

> One last bit: I try to contact you because I have a really simple Addon Idea which would be amazing if you can code it.

So this part is off-topic here :stuck_out_tongue_closed_eyes: 

> I just need a toggle for switching dom.event.clipboardevents.enabled on and off.

After doing some searching my guess is that you need this to block pages from blocking "Copy and Paste". If that's the case, then please use: https://addons.mozilla.org/firefox/addon/don-t-fuck-with-paste/

> I would be happy to donate some coffee by PayPal for that!

Thank you but I usually don't take any money for my open source work.

Closing because all your requirements are fulfilled by other Add-ons and I'm no fan of reinventing wheels at all :smiley:

**Comment by 6xthFNGR** [comment]
Hello,

well matrix vs vector arguments besides, they still is a users need like in my case to have a 1-click solution and safe it as PDF. Sadly, the suggested addon (Print Edit We) is not suitable for this application.
If you want to consider PDF export in the future, I would be glad.

About the Offtopic:
Is there any way to contact you? dom.event.clipboardevents.enabled is another feature than your addon suggestion interfaces with. As many websites break so copy/pasting by the host OS ist not possible anymore due to JS using this feature, it would be great to have a toggle for it. By default, this option should be set deactivated, for granting additional security. As there is no other tool using this, you would be the only one offering such, and as much as I love open source or even free and open source software, I would still consider to offer you a coffee and icecream if you would create such app because I dont have time to get into firefox and create my first app - I wanna stay a User, so I would like to support a dev.

Thanks again

**Comment by M-Reimer** [comment]
"Print Edit WE" does offer something close to what you need. Click the button. Choose "Save" in the toolbar and select "PDF". Select the target format. Done.

About the "copy/pasting". Exactly there the suggested Add-on should help. If it doesn't work for a particular case, then maybe file an Issue for this Add-on.

**Comment by M-Reimer** [comment]
Maybe I should add a few background informations.

About the PDF support:
- I don't think that it is a good idea to export a PDF which contains a raster image. In this case the PDF "container" is just unneeded ballast which does not add any benefit.
- Exporting to PDF requires a completely different API which has its own limitations and does not fit into my existing Add-on at all. I was developer of an "all in one Add-on" in the past and this was horrible experience. By doing this I've learned an important lesson: Keep Add-ons small and make them do one job very good.
- I recommended "Print Edit WE" because I use it a lot to prepare websites before printing them. It just happens to have the feature of saving to PDF so I did not have to install something else. There are other PDF save Add-ons available. For example this one could maybe fit your needs even better: https://addons.mozilla.org/firefox/addon/foxytab/

About the "dom.event.clipboardevents.enabled" stuff:
- If your whole goal was to toggle this preference, then I can tell you that this is _100% impossible_! Add-ons can only change a very limited subset of all preferences. Meaning around 10 or so and they have to be accessed using dedicated API. You can't just name the preference you want to read or set. So to achieve a particular goal with an Add-on in most cases alternative solutions have to be used as changing "about:config" preferences usually is no option. That's why I recommended an Add-on which seems to do just that.
