### ISSUE TITLE
Improve handling of static & absolute positioned HTML elements

### ISSUE THREAD

**Issue by Gitoffthelawn** [M-Reimer/savescreenshot#45]
One of the things that drew me to this extension was that, in initial testing, it seemed to handle static & absolute positioned elements (often headers or footers) better than the tool I've been using for years.

Unfortunately, after more use, I've found that this extensions isn't handling some web pages with static or absolute positioned elements too well.  Typically, in the resultant screenshots, the static/absolute positioned elements overwrite part of the page's content.  These are always long pages that do not fit in the viewport (and I'm trying to capture the entire page).

If it helps you, I can try to keep a list of sites I encounter on which this happens.  So far, it's all been on pages of websites that are not public-facing.  But that's largely because those are the ones that I most frequently have a use to capture screenshots.

**Comment by M-Reimer** [comment]
There may be some major difference between the Add-ons, you tried so far, and my attempt of creating a simple screenshot Add-on. My goal was to go the simplest way. And for Firefox this is to use its built in interface for requesting full page screenshots and create a somewhat useful user interface around it.

So the whole screenshot job is actually done by Firefox. Not much I can do there. In fact it is close to impossible to create good screenshots for every website out there. Screenshot Add-ons are usually made for "linear" pages without fancy embedded scrollable "windows".

The only way to make this possible would be to write a stylesheet which specifically helps taking screenshots for one particular page. Then I could apply this stylesheet before taking the screenshot and remove it afterwards. But, of course, this is only useful for "public-facing" websites and I would only do this for big players also.

So if you have problems with some private "intra net" sites, then probably there is not much I can do for you.

**Comment by Gitoffthelawn** [comment]
Thanks.  I didn't realize that you were using the internal Firefox API for the screenshot.  That certainly does make things harder to tweak.

My other favourite screenshot tool is Page Saver WE (https://addons.mozilla.org/firefox/addon/pagesaver-we/).  It was having some troubles capturing a page with static/absolute elements, so I tried your extension (your name was familiar to me for other good stuff), and it worked much better for that page.  I'm an optimist, so I hoped it that improvement would translate to most other pages, but my optimism let me down a bit on this one! :)  That's okay... I'll still choose to be an optimist. :)

IIRC, Page Saver WE uses it's own technique to scroll the page to capture the entire thing.  It's been a long while since I've looked at its source code, so don't quote me on that!

Since your extension uses the native Firefox API, it what ways (if any) does the output differ from the native Firefox screenshot tool that's integrated with the browser?  Or is it the same output, but with better options of how to name the output file (and now which folder to place it in... thanks!) along with a useful toolbar button?

**Comment by M-Reimer** [comment]
> I didn't realize that you were using the internal Firefox API for the screenshot. That certainly does make things harder to tweak.

In theory this is not a problem at all. You have to use Firefox APIs in all cases. The Add-ons, that do scrolling on their own, just don't utilize the "Firefox only" feature for taking full page screenshots. In all Add-ons that exist for both, Firefox and Chrome, it is likely that the developer only uses what both browsers support. And as I don't care about Google Chrome (and Chromium) AT ALL this is no issue for me.

The problem is that some "creative" website designs simply make it impossible to know how to scroll individual segments of the page properly to get "the perfect" screenshot. Simple screenshots depend on the page scrolling in the &lt;body&gt; element. The "proper" way to create a full page screenshot of pages that don't scroll in &lt;body&gt; is to modify this website temporarily. This requires to create a custom CSS which is applied temporarily while creating the screenshot.

> Since your extension uses the native Firefox API, it what ways (if any) does the output differ from the native Firefox screenshot tool that's integrated with the browser?

It is the same output. I just simplified the whole interface a lot while still adding features Firefox itself does not have. Like more configuration options, "one click screenshots" and all the shortcut options which allows to create the screenshot type you need with a user defined keyboard shortcut.
