### ISSUE TITLE
No total screenshot

### ISSUE THREAD

**Issue by Zorroblanco** [M-Reimer/savescreenshot#5]
Hi, I cant take total screenshot for this web https://marcjapan.wordpress.com/2010/08/08/recopilatorio-curso-de-japones/  (Firefox 56.0.2 win 7 x86), it take screenshot from begining to comment enero 11 2013 . Thanks in advance (sorry for my english, I hope you understand)

**Comment by M-Reimer** [comment]
There always has been a limit in the possible size but I didn't have a look at this part of code since many years.
I searched the Firefox sourcecode for the relevant code parts to find out the exact limit values:
https://github.com/M-Reimer/savescreenshot/commit/0922f27505671bcfe9864c4f7e727912d681ba2c
The actual limit is the positive limit if an 32bit signed integer value which means that width and height can have a maximum of 32767 pixels.
I've changed my code to this values. This still isn't enough to cover your very long website but gives about twice as much content in the resulting picture as before.
I don't have the time to do a new release, today, but you can give this a try by temporarily installing the new version after downloading the GIT snapshot.

**Comment by Zorroblanco** [comment]
Thanks for your answer! I ll wait for your release, (I dont know how to installing this, sorry). Thanks again. Cheers

**Comment by Zorroblanco** [comment]
Hi, I can use new modification, but now I cannot take screenshot "Failed to take screenshot! It is not possible to create a screenshot from this page" (working in for example rutracker, reddit, github) Cheers

**Comment by Zorroblanco** [comment]
Hi, I can use new modification, but now I cannot take screenshot "Failed to take screenshot! It is not possible to create a screenshot from this page" (working in for example rutracker, reddit, github) Cheers

**Comment by Zorroblanco** [comment]
Hi, I can use new modification, but now I cannot take screenshot "Failed to take screenshot! It is not possible to create a screenshot from this page" (working in for example rutracker, reddit, github) Cheers

**Comment by Zorroblanco** [comment]
Hi, I can use new modification, but now I cannot take screenshot "Failed to take screenshot! It is not possible to create a screenshot from this page" (working in for example rutracker, reddit, github) Cheers

**Comment by M-Reimer** [comment]
Thanks for testing.
That's interesting. For me this worked just well.
Do you use a 32bit operating system? But even there hardcoded int32_t should have exactly this size...
Can you provide some information about your setup?

**Comment by M-Reimer** [comment]
I've pushed the larger limits as part of the 2.2.0 update.
I've tested this on any system I could get hold of.
If there are problems with the large limits, please open a new issue with detailed info and test page URL.
